site_name: My Docs
site_description: Documentation for the strom project
theme: readthedocs
pages:
- Index: 'index.md'
- Project Components:
    - DStreams: 'dstream.md'
    - Web Sockets: 'web_sockets.md'
